### ISSUE TITLE
Support pointer is wrong

### ISSUE THREAD

**Issue by patmc2go** [ibm-cloud-docs/was-for-vsi#2]
This doc sends people to the Cloud support center - but when you create a ticket there for this product offering, you get a pop-up that redirects you to /mysupport:
> https://www.ibm.com/mysupport/s/createrecord/NewCase

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/12019963/140769374-289163ac-cd2f-46a5-926d-09e95bab0184.png">

Please correct this doc.    

Note:  I was looking at this as we have a client who did open a ticket in the cloud support center because they don't know how to create an account on the /mysupport portal.   So anything you can add to help with that is a plus.

**Comment by helyarp** [comment]
@patmc2go URL and link text updated as you suggest. Pls review at https://test.cloud.ibm.com/docs-draft/was-for-vsi?topic=was-for-vsi-support
